version: "2"
services:
  server_sample:
    container_name: server_sample
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - apm
      - postgres
    links:
      - apm
      - minio
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=true
      - discovery.type=single-node
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.6.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_PORT=9200
      - SERVER_HOST=0.0.0.0
      - XPACK_SECURITY_ENABLED=true
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWD=changeme
      - XPACK_GRAPH_ENABLED=true
      - XPACK_WATCHER_ENABLED=true
      - XPACK_ML_ENABLED=true
      - XPACK_MONITORING_ENABLED=true
      - XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  apm:
    container_name: apm
    image: docker.elastic.co/apm/apm-server:6.6.1
    environment:
      - output.elasticsearch.hosts=http://elasticsearch:9200
      - apm-server.host=localhost:8200
    ports:
      - "8200:8200"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin0000
    command: server /data
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d/

#version: "3"
#services:
#    db:
#        image: "mcr.microsoft.com/mssql/server:latest"
#        environment:
#            SA_PASSWORD: "MyPass2020"
#            ACCEPT_EULA: "Y"
#        ports: 
#            - "1433:1433"